INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_USRPCALIBRATOR usrpcalibrator)

FIND_PATH(
    USRPCALIBRATOR_INCLUDE_DIRS
    NAMES usrpcalibrator/api.h
    HINTS $ENV{USRPCALIBRATOR_DIR}/include
        ${PC_USRPCALIBRATOR_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    USRPCALIBRATOR_LIBRARIES
    NAMES gnuradio-usrpcalibrator
    HINTS $ENV{USRPCALIBRATOR_DIR}/lib
        ${PC_USRPCALIBRATOR_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(USRPCALIBRATOR DEFAULT_MSG USRPCALIBRATOR_LIBRARIES USRPCALIBRATOR_INCLUDE_DIRS)
MARK_AS_ADVANCED(USRPCALIBRATOR_LIBRARIES USRPCALIBRATOR_INCLUDE_DIRS)

